lokalise/shared-ts-libs

packages/app/backend-http-client/index.ts, packages/app/backend-http-client/package.json, packages/app/backend-http-client/src/httpClient.spec.ts, packages/app/backend-http-client/src/httpClient.ts, packages/app/backend-http-client/tsconfig.json, packages/app/backend-http-client/vitest.config.mts
This ensures that we are following our best practices for making HTTP requests - set label for easier debugging and require schema for type-safe response handling.
=> Enforce stricter constraints on HTTP client params

packages/app/prisma-utils/src/cockroachdbError.spec.ts, packages/app/prisma-utils/src/cockroachdbError.ts, packages/app/prisma-utils/src/index.ts, packages/app/prisma-utils/src/prismaTransaction.spec.ts, packages/app/prisma-utils/src/prismaTransaction.ts, packages/app/prisma-utils/src/types.ts, packages/app/prisma-utils/vitest.config.mts
We have the following error:
```
Transaction failed with unrecoverable error: {"name":"PrismaClientKnownRequestError","code":"P2010","clientVersion":"5.13.0","meta":{"code":"40001","message":"restart transaction: TransactionRetryWithProtoRefreshError: WriteTooOldError: write for key ...
```
Following [crdb doc](https://www.cockroachlabs.com/docs/stable/transaction-retry-error-reference#:~:text=To%20indicate%20that%20a%20transaction,the%20string%20%22restart%20transaction%22%20.)
> All transaction retry errors use the SQLSTATE error code 40001, and emit error messages with the string [restart transaction](https://www.cockroachlabs.com/docs/v24.1/common-errors#restart-transaction). Further, each error includes a [specific error code](https://www.cockroachlabs.com/docs/stable/transaction-retr …
=> Crdb transaction retry

packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts, packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
Please describe
- fix setting `x-request-id` in resolveExecutionLogger
- expose logJobStarted method
- expose logJobFinished method
=> chore(background-jobs-common): extract start and finish logs to dedicated methods

packages/app/error-utils/src/bugsnag.spec.ts, packages/app/error-utils/src/bugsnag.ts, packages/app/error-utils/src/index.spec.ts
Adding internal error and public error details to Bugsnag context by default so we can avoid doing it manually
=> Bugsnag report error details

packages/app/prisma-utils/package.json, packages/app/prisma-utils/src/prismaTransaction.spec.ts, packages/app/prisma-utils/src/prismaTransaction.ts, packages/app/prisma-utils/src/types.ts
Prisma transaction incorporates a exponential backoff retry with 100ms as default base delay
=> Prisma transaction retry delay

packages/app/websockets-common/src/rooms.ts
[AP-3831](https://lokalise.atlassian.net/browse/AP-3831)
Adds a `shopify` websockets room using a new `INTEGRATION_ID_SCHEMA`
[AP-3831]: https://lokalise.atlassian.net/browse/AP-3831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add shopify websockets room

packages/app/api-common/src/paginationUtils.ts
Update cursor position as part of `getPaginatedEntriesByHasMore` fx
=> fix: update cursor as part of getPaginatedEntriesByHasMore

.github/dependabot.yml
ESLint 9 requires migration, and next vitest semver minor requires ESLint 9
=> Add dependabot ignores

packages/app/backend-http-client/.eslintrc.json, packages/app/backend-http-client/src/client/httpClient.spec.ts, packages/app/backend-http-client/src/client/httpClient.ts
Make it easier to identify which requests failed with validation errors by adding requestLabel
=> Add requestLabel to request zod errors

packages/app/error-utils/src/bugsnag.spec.ts, packages/app/error-utils/src/bugsnag.ts
With this PR we expect to cover all types of error containing `details` field
=> Filling errorDetails for unknown errors

packages/dev/eslint-config/package.json
This fixes compatibility with ESLint 8 by using correct vitest plugin version
=> Use correct plugin version

packages/app/api-common/src/paginationUtils.ts
By looking at current method description, it was not clear that the method not only sets meta, but also slices the data to `pageLimit` length. Added information about it.
=> Updated createPaginatedReponse params description

packages/app/events-common/src/baseEventSchemas.ts
We do not always control the correlationId of a request that initiates the chain, so we should be flexible in what we accept there.
=> Accept any string as a correlationId

packages/app/prisma-utils/src/prismaError.ts, packages/app/prisma-utils/src/prismaTransaction.spec.ts, packages/app/prisma-utils/src/prismaTransaction.ts, packages/app/prisma-utils/src/types.ts
Feature to auto-increase timeout in case it is the error on the transaction
=> Transaction auto increase timeout

packages/dev/biome-config/configs/biome-base.jsonc
It is pretty normal to use non-null assertions in tests.
=> Allow non-null assertions in tests

packages/dev/biome-config/configs/biome-base.jsonc
The "vitest" string did not work as expected. The variables have to be all listed in there.
=> fix: add vitest globals to biome base config

packages/app/backend-http-client/README.md, packages/app/backend-http-client/index.ts, packages/app/backend-http-client/src/client/constants.ts, packages/app/backend-http-client/src/client/httpClient.spec.ts, packages/app/backend-http-client/src/client/httpClient.ts, packages/app/backend-http-client/src/client/types.ts
adding support for `204`, same as we did for FE client
=> http client 204 support

packages/app/backend-http-client/package.json, packages/dev/biome-config/configs/biome-base.jsonc
This change allows for `test` folder to be nested.
In FE, we have usually test folder nested within `src/test/whatever-file.ts`.
=> fix: allow test folder to be nested

packages/app/background-jobs-common/biome.json, packages/app/background-jobs-common/package.json, packages/dev/biome-config/README.md, packages/dev/biome-config/configs/biome-package.jsonc, packages/dev/biome-config/package.json
=> Adding biome.package.json

packages/dev/eslint-config-biome-companion/README.md
This adds instructions for how to add companion ESLint setup (to Biome) for FE projects.
FYI: the name follows the [eslint naming convention for shareable packages](https://eslint.org/docs/latest/extend/shareable-configs#creating-a-shareable-config) (starting with `eslint-config...`)
=> feat: add eslint-config-biome-companion

packages/dev/biome-config/README.md
The README references `biome-packages.jsonc` but it's actually `biome-package.jsonc`
=> Fix typo in README

.github/workflows/ci.yml, packages/dev/package-vite-config/package.json
See https://nodejs.org/en/blog/release/v22.5.1
=> Pin Node version to a fixed one

packages/app/healthcheck-utils/package.json, packages/app/healthcheck-utils/src/HealthcheckRefreshJob.spec.ts, packages/app/healthcheck-utils/src/HealthcheckResultsStore.spec.ts, packages/app/healthcheck-utils/src/HealthcheckResultsStore.ts, packages/app/healthcheck-utils/src/healthchecks.ts
Previously it will only register Gauges for the very first healthcheck.
=> Use separate checks for separate healthchecks

packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts, packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts, packages/app/background-jobs-common/src/background-job-processor/spy/BackgroundJobProcessorSpy.ts, packages/app/background-jobs-common/src/background-job-processor/types.ts
[Repeatable jobs](https://docs.bullmq.io/guide/jobs/repeatable) can be scheduled by passing the repeat settings. However, these settings are only accepted when using the [add()](https://github.com/taskforcesh/bullmq/blob/c60e6a3f45606c623ef6a2b16415d67eac9b0269/src/classes/queue.ts#L218) method and are ignored when using [addBulk()](https://github.com/taskforcesh/bullmq/blob/c60e6a3f45606c623ef6a2b16415d67eac9b0269/src/classes/queue.ts#L264) where [they are omitted](https://github.com/taskforcesh/bullmq/blob/c60e6a3f45606c623ef6a2b16415d67eac9b0269/src/interfaces/minimal-job.ts#L5). This PR uses `add()` instead of reusing `scheduleBulk()` in the `schedule()` method so that repeatable jobs can be scheduled and prevents this from happening in the future shall they introduce additional …
=> MET-188 Add support for repeatable jobs

packages/app/universal-ts-utils/src/array/isNonEmptyArray.spec.ts, packages/app/universal-ts-utils/src/array/isNonEmptyArray.ts
Adding `isNonEmptyArray` method to facilitate working with `nonempty` constraint from Zod
=> Adding isNonEmptyArray

packages/dev/package-vite-config/package.json
Moved the vite/vitest dependencies to `peerDependencies`. This will allow better de-duplication in the consuming packages. Also made the versions to be range rather being pinned to specific version.
=> fix: move vite/vitest dependencies to peerDependencies

packages/app/universal-ts-utils/package.json
Objective was to, on BE, be able to use `import {...} from '@lokalise/universal-ts-utils/node'` but it does not work as /dist is still needed (`@lokalise/universal-ts-utils/dist/node`).
With this PR I am trying to fix it, but I am not sure if it will work as desired or not, so please feel free to let me know if you disagree with the change or know how to achieve it 🙏
=> Trying to fix node import for BE

packages/app/prisma-utils/README.md, packages/app/prisma-utils/package.json, packages/app/prisma-utils/prisma/schema.prisma, packages/app/prisma-utils/src/index.ts, packages/app/prisma-utils/src/plugins/CollectionScheduler.ts, packages/app/prisma-utils/src/plugins/MetricsCollector.ts, packages/app/prisma-utils/src/plugins/prismaMetricsPlugin.spec.ts, packages/app/prisma-utils/src/plugins/prismaMetricsPlugin.ts, packages/app/prisma-utils/src/prismaClientFactory.spec.ts
=> AP-5778 introduce prisma metrics plugin

packages/app/universal-ts-utils/biome.json, packages/app/universal-ts-utils/src/internal/compare.spec.ts, packages/app/universal-ts-utils/src/public/array/areStringArraysEqual.spec.ts, packages/app/universal-ts-utils/src/public/array/callChunked.spec.ts, packages/app/universal-ts-utils/src/public/array/chunk.spec.ts, packages/app/universal-ts-utils/src/public/array/isNonEmptyArray.spec.ts, packages/app/universal-ts-utils/src/public/array/removeFalsy.spec.ts, packages/app/universal-ts-utils/src/public/array/removeNullish.spec.ts, packages/app/universal-ts-utils/src/public/array/sort.spec.ts, packages/app/universal-ts-utils/src/public/array/sort.ts, packages/app/universal-ts-utils/src/public/array/sortByField.spec.ts, packages/app/universal-ts-utils/src/public/array/sortByField.ts, packages/app/universal-ts-utils/src/public/array/unique.spec.ts, packages/app/universal-ts-utils/src/public/object/areDeepEqual.spec.ts, packages/app/universal-ts-utils/src/public/object/groupBy.spec.ts, packages/app/universal-ts-utils/src/public/object/groupBy.ts, packages/app/universal-ts-utils/src/public/object/groupByUnique.spec.ts, packages/app/universal-ts-utils/src/public/object/groupByUnique.ts
Trying to fix:
```
Error: Cannot find module '.../node_modules/@lokalise/universal-ts-utils/dist/internal/compare' imported from .../node_modules/@lokalise/universal-ts-utils/dist/public/array/sort.js
```
=> Trying to fix imports on universal-ts-utils

packages/app/background-jobs-common/package.json
Restricts BullMQ to the latest compatible version to address breaking changes due to incompatible generic types.
=> Restrict BullMQ to the latest compatible version

packages/app/script-utils/src/vault/vault.ts
Minor change, explained in error log that 403 might be reported due to invalid secrets path.
=> Vault env var sync indicates that 403 might be due to invalid path.

packages/app/background-jobs-common/package.json, packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.spec.ts, packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.ts, packages/app/background-jobs-common/src/periodic-jobs/periodicJobTypes.ts
Periodic jobs work without all the dependencies that are currently mandatory, so we can relax the requirements a bit
=> Make abstract periodic job configuration more flexible

packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.ts
Disabled single consumer mode shouldn't require redis either.
=> Fix Redis check

packages/app/universal-ts-utils/src/node.ts, packages/app/universal-ts-utils/src/public/string/trimText.spec.ts, packages/app/universal-ts-utils/src/public/string/trimText.ts
Adding utility to trim a text but contemplating HTML space and in addition can return the trimmed part in case it is needed
=> Trim text util

packages/dev/biome-config/configs/biome-esm.jsonc
Previously TSX files would use `ts` extension instead of `js`
=> Support TSX for ESM rule

packages/app/universal-ts-utils/README.md, packages/app/universal-ts-utils/package.json
This PR improves the exports config in universal-ts-utils package.json.
After the changes, adding explicit extensions when importing an util will be forbidden, and the import will be automatically resolved to the js file.
Thanks to this change IDE will no longer list .dts or source map files in imports autocomplete
This is a MAJOR change, as every `*.js` import will have to be replaced with an extensionless one
```
import { mapNonEmptyArray } from '@lokalise/universal-ts-utils/array/mapNonEmptyArray.js'
into
import { mapNonEmptyArray } from '@lokalise/universal-ts-utils/array/mapNonEmptyArray'
```
For more info, please take a look into: https://hirok.io/posts/package-json-exports#subpaths-resolution-advanced
=> improve exports config for universal ts utils

packages/app/background-jobs-common/package.json, packages/app/background-jobs-common/src/background-job-processor/managers/FakeQueueManager.ts, packages/app/background-jobs-common/src/background-job-processor/managers/JobRegistry.ts, packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts, packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
This relies on another PR, hence targetting non-main. The idea here is to resolve specific job payload based on queueId provided.
Currently missing:
* Documentation
* Tests were not updated
* BaseJobPayload enforcement is not working
=> feat: type-safe queueManager

packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts
This change allows to properly infer response type in case preprocessing on response is used. To achieve that we need to use different type inference for input and output values
=> Type inference improvement

packages/app/fastify-api-contracts/package.json, packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts, packages/app/fastify-api-contracts/src/fastifyApiContracts.ts, packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts
With previous approach, preprocessed schema properties were not inferred properly, and resolved to unknown. This PR solves it by using schemas as generics params and explicit `z.infer<>` for types
=> Fastify api contracts type improvements

packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts, packages/app/fastify-api-contracts/src/fastifyApiContracts.ts, packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts, packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts
Without types propagation, it wasn't possible to generate handler for contract that uses `isNonJSONResponseExpected` or `isEmptyResponseExpected`
=> Added support for isNonJSONResponseExpected and isEmptyResponseExpected in fastify api contracts

packages/app/background-jobs-common/README.md, packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts, packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts, packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.barrier.spec.ts, packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.error.spec.ts, packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.repeatable.spec.ts, packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.spy.spec.ts, packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.stalled.spec.ts, packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.start.spec.ts, packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.success.spec.ts, packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts, packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessorNew.ts, packages/app/background-jobs-common/src/background-job-processor/processors/types.ts, packages/app/background-jobs-common/test/TestDependencyFactory.ts, packages/app/background-jobs-common/test/processors/TestBarrierBackgroundJobProcessorNew.ts, packages/app/background-jobs-common/test/processors/TestFailingBackgroundJobProcessorNew.ts, packages/app/background-jobs-common/test/processors/TestOverrideProcessBackgroundProcessor.ts, packages/app/background-jobs-common/test/processors/TestReturnValueBackgroundJobProcessorNew.ts, packages/app/background-jobs-common/test/processors/TestStalledBackgroundJobProcessorNew.ts, packages/app/background-jobs-common/test/processors/TestSuccessBackgroundJobProcessorNew.ts
With this PR, we are sharing the spy instance between the processor and queue manager, which helps to have better visibility on the real state of the job.
Also, we are removing `isTest` and `redisConfig` from the processor config, it will now be taken from the queue manager. This helps to simplify config and avoid configuration issues (eg, having queue and processor with different redis instances)
=> bg processor shared spy instance

packages/app/api-common/src/cursorCodec.ts, packages/app/api-common/src/index.ts, packages/app/api-common/test/cursorCodec.spec.ts, packages/app/api-common/vite.config.ts
In the browser, we cannot use Buffer for cursor encoding. Therefore, within this change, `btoa` and `atob` functions will be used when Buffer is not available
=> Browser compatible cursor encoding

packages/app/frontend-http-client/package.json
This PR renames build script so that it can be used with turborepo.
Also, it adds universal-ts-utils to devDeps, so turbo can build it before building fe-http-client.
=> fix(frontend-http-client): build with turborepo

packages/app/fastify-api-contracts/README.md
We are actually using this pattern, but it wasn't documented anywhere
=> docs: Add documentation for handler/route separation

.github/workflows/release.tsconfig.yml, packages/app/non-translatable-markup/package.json, packages/app/non-translatable-markup/tsconfig.build.json, packages/app/non-translatable-markup/tsconfig.json, packages/app/non-translatable-markup/vitest.config.ts, packages/dev/tsconfig/LICENSE.md, packages/dev/tsconfig/README.md, packages/dev/tsconfig/configs/base.json, packages/dev/tsconfig/configs/build-app.json, packages/dev/tsconfig/configs/build-private-lib.json, packages/dev/tsconfig/configs/build-public-lib.json, packages/dev/tsconfig/configs/bundler-dom.json, packages/dev/tsconfig/configs/bundler.json, packages/dev/tsconfig/configs/tsc-dom.json, packages/dev/tsconfig/configs/tsc.json, packages/dev/tsconfig/package.json
This PR adds a sharable tsconfig package. As an example, this package is used for `non-translatable-markup`.
=> chore: add sharable tsconfig package

packages/dev/tsconfig/configs/base.json, packages/dev/tsconfig/configs/build-app.json
This PR enables `.ts` extension usage that will be rewritten into `.js` during the build process.
=> chore: enable ts extension usage

packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts
Request injection doesn't really care what are the fastify app generics, so we can relax our requirements there
=> fix: Accept any fastify instance

packages/app/frontend-http-client/README.md, packages/app/frontend-http-client/package.json, packages/app/frontend-http-client/src/client.spec.ts, packages/app/frontend-http-client/src/client.ts, packages/app/frontend-http-client/src/index.ts, packages/app/frontend-http-client/src/utils/bodyUtils.ts, packages/app/frontend-http-client/src/utils/errorUtils.ts, packages/app/frontend-http-client/tsconfig.json
I've added the function that allows sending `POST` request and track its progress. This will be used for tracking file upload and has been implemented as a result of the conversation [here](https://github.com/lokalise/autopilot/pull/5354#discussion_r1971286655)
=> AP-6426 added `sendPostWithProgress()` util function

packages/app/fastify-api-contracts/README.md, packages/app/fastify-api-contracts/package.json, packages/app/fastify-api-contracts/src/fastifyApiContracts.metadataMapper.spec.ts, packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts, packages/app/fastify-api-contracts/src/fastifyApiContracts.ts, packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts, packages/app/fastify-api-contracts/src/index.ts, packages/app/fastify-api-contracts/src/types.ts
Use api-contracts library instead of universal-utils
=> Switch to consume api-contracts lib

packages/app/fastify-api-contracts/src/fastifyApiContracts.ts, packages/app/fastify-api-contracts/src/types.ts, packages/app/universal-ts-utils/src/public/api-contracts/__snapshots__/apiContracts.spec.ts.snap, packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts
This PR improves API contract definition, used for generating OpenApi schemas:
- Add summary property to API contracts
- Pass-through description to schema.description
=> chore: Add summary to API contracts and pass-through description

packages/app/frontend-http-client/package.json, packages/app/frontend-http-client/src/client.spec.ts
Illustrate that use-case works as expected
=> Add test for type inference when handling multiple query values, separated by commas

packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts, packages/app/fastify-api-contracts/src/fastifyApiContracts.ts, packages/app/fastify-api-contracts/src/types.ts
Narrowing down Fasrtify route type to improve type checks on services and `opinionated-machine`
=> Fastify API contracts Route type narrowing down types

packages/app/fastify-api-contracts/package.json, packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts, packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
This ensures that GET contracts work fine with empty responses
=> fix: Properly handle empty responses for non-payload routes

packages/app/fastify-api-contracts/src/types.ts
Trying to fix build issues caused by the auto-inferred logger and typeProvider
=> Fixing the route type to allow any type provider and logger

packages/app/fastify-api-contracts/README.md, packages/app/fastify-api-contracts/src/fastifyApiContracts.metadataMapper.spec.ts, packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts, packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
We could then rely on contract metadata in our plugins directly.
=> Expose contract on a route

packages/app/frontend-http-client/README.md, packages/app/frontend-http-client/src/client.spec.ts, packages/app/frontend-http-client/src/client.ts
Added possibility to pass `AbortController` to abort request made by `sendPostWithProgress()`. This will be used to stop pending file uploads/
=> AP-6857 Allow aborting the request made by calling `sendPostWithProgress()`

packages/app/background-jobs-common/README.md, packages/app/background-jobs-common/package.json, packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.spec.ts, packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.ts, packages/app/background-jobs-common/src/periodic-jobs/periodicJobTypes.ts
This allows awaiting for the job to be executed before proceeding
=> feat: Expose asyncRegister for periodic jobs

packages/app/healthcheck-utils/README.md, packages/app/healthcheck-utils/package.json, packages/app/healthcheck-utils/src/HealthcheckResultsStore.spec.ts, packages/app/healthcheck-utils/src/HealthcheckResultsStore.ts
We now preemptively populate healthcheck store, and always assume that if value is not there, check has failed.
=> Remove staleness parameter, we always depend on the data available

packages/app/prisma-utils/package.json
CI started failing again, pinning version to avoid
=> Make prisma-utils CI more predictable by pinning dependency

packages/app/backend-http-client/package.json, packages/app/backend-http-client/src/client/apiContractTypes.ts, packages/app/backend-http-client/src/client/constants.ts, packages/app/backend-http-client/src/client/httpClient.spec.ts, packages/app/backend-http-client/src/client/httpClient.ts, packages/app/backend-http-client/src/client/types.ts, packages/app/frontend-http-client/src/client.spec.ts
Underlying libraries need to be updated to start using and expecting v4 zod, meanwhile we can start preparing by bumping the dependency version and pinning classic version explicitly.
=> Update zod for backend-http-client

packages/app/background-jobs-common/README.md, packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts, packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts, packages/app/background-jobs-common/src/background-job-processor/managers/types.ts
This PR allows the use of a function that will be resolved for every scheduled job for `jobOptions`
```
{
queueId: LqaAsyncReviewJobProcessor.QUEUE_ID,
jobPayloadSchema: LQA_ASYNC_REVIEW_JOB_DATA,
jobOptions(payload:any): {
return {
group: {
id: payload.withTenantGrouping ? payload.tenantId : payload.key,
}
}
}
},
```
=> Add option to set job options as a function

packages/app/background-jobs-common/src/background-job-processor/errors/MutedUnrecoverableError.ts
Add details to `MutedUnrecoverableError`, so we can maintain some data from initial error when rethrowing this one.
Context: https://github.com/lokalise/content-type-app-engine/pull/567#discussion_r2178303680
=> feat: add details to MutedUnrecoverableError

packages/app/background-jobs-common/package.json, packages/app/fastify-bullboard-plugin/package.json, packages/app/universal-ts-utils/README.md, packages/app/universal-ts-utils/src/node.ts, packages/app/universal-ts-utils/src/public/type/assertIsNever.test.ts, packages/app/universal-ts-utils/src/public/type/assertIsNever.ts, packages/dev/biome-config/configs/biome-base.jsonc
FINALLY lift a utility function that I have written a number of times into a shared utility.
The `assertIsNever` method asserts that the provided value is of type `never` and will cause a TypeScript error if it is not.
This is useful for exhaustive type checking in switch statements or conditional types, ensuring that all possible cases have been handled.
```typescript
const value: "case1" | "case2" = getSomeValue();
switch (value) {  
case 'case1':    
return 'Handled case1';  
case 'case2':    
return 'Handled case2';  
default:    
// This will trigger an error if there are unhandled cases    
return assertIsNever(value);
}
```
=> feat: assert is never utility function

packages/app/api-contracts/package.json, packages/app/api-contracts/src/apiContracts.ts, packages/app/api-contracts/vitest.config.ts, packages/app/backend-http-client/package.json, packages/app/backend-http-client/src/client/httpClient.ts, packages/app/fastify-api-contracts/package.json, packages/app/fastify-api-contracts/src/fastifyApiContracts.response-types.spec.ts, packages/app/fastify-api-contracts/src/fastifyApiContracts.ts, packages/app/frontend-http-client/package.json, packages/app/frontend-http-client/src/client.ts, packages/app/universal-testing-utils/package.json, packages/app/universal-testing-utils/src/MockttpHelper.spec.ts, packages/app/universal-testing-utils/src/MockttpHelper.ts, packages/app/universal-testing-utils/src/MswHelper.spec.ts, packages/app/universal-testing-utils/src/MswHelper.ts, packages/app/universal-testing-utils/vitest.config.ts
Accept not only successful responses, but also values adhering to one of the error schemas.
=> feat: support union types on responses

packages/app/aws-config/package.json
Trying to get around this error when trying to update to zod 4 & company:
It is only this peer dependency that is on fastify-extras 27, as all dev ones are on 30 already. We're planning to update Autopilot and Maestro to zod 4 and fastify-extras 30 as well, so while this is a breaking change it hopefully won't cause disruptions.
=> chore: bump peer fastify-extras in aws-config

packages/app/api-contracts/package.json, packages/app/api-contracts/src/apiContracts.ts, packages/app/api-contracts/src/index.ts, packages/app/api-contracts/src/pathUtils.spec.ts, packages/app/api-contracts/src/pathUtils.ts, packages/app/backend-http-client/README.md, packages/app/backend-http-client/src/client/apiContractTypes.ts, packages/app/backend-http-client/src/client/httpClient.spec.ts, packages/app/backend-http-client/src/client/httpClient.ts, packages/app/frontend-http-client/README.md, packages/app/frontend-http-client/src/client.spec.ts, packages/app/frontend-http-client/src/client.ts, packages/app/frontend-http-client/src/types.ts
Adds `pathPrefix` optional param to api-contract related types in `backend-http-client` and `frontend-http-client`
=> EXP-823 use path prefix with api contracts
