packages/app/websockets-common/src/rooms.ts

See for more details: https://lokalise.slack.com/archives/C05E5H778QP/p1716290285604619

feat(AP-3587): add optional languageId to CM WS event schema

---

packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts

Removing logs on success to reduce space usage

clean logs on success

---

packages/app/api-common/src/paginationUtils.ts
packages/app/api-common/test/paginationUtils.spec.ts

* improve pagination tests

---

packages/app/backend-http-client/index.ts
packages/app/backend-http-client/src/client/httpClient.ts

Reduces amount of boilerplate in cases where we don't care about extra metadata

Add test options

---

packages/app/id-utils/README.md
packages/app/id-utils/package.json
packages/app/id-utils/src/index.spec.ts
packages/app/id-utils/src/index.ts

AP-3814 Added uuid 7.

---

packages/dev/biome-config/configs/biome-base.jsonc

- Adding `"./**/*.test.ts", "./**/*.test.tsx", "./test/**/*"` to biome tests override

Adding test files to biome override

---

packages/dev/biome-config/package.json

biome 1.2.0

---

packages/dev/biome-config/package.json

biome - adding missing script required for release

---

packages/dev/biome-config/configs/biome-frontend.jsonc

This PR adds Frontend configuration to our frontend biome config.

fix: add frontend specific rules to biome config

---

packages/app/backend-http-client/package.json

Fixing release

---

packages/app/background-jobs-common/package.json

Bump to retrigger failed release

MET-160 Bump node

---

packages/app/background-jobs-common/package.json

MET-160 Bump rimraf

---

packages/app/background-jobs-common/package.json
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spy.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessor.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessor.ts
packages/app/background-jobs-common/test/processors/TestFailingBackgroundJobProcessor.ts
packages/app/background-jobs-common/test/processors/TestSucessBackgroundJobProcessor.ts
packages/app/background-jobs-common/tsconfig.json
packages/app/background-jobs-common/vitest.config.mts

Fixing usage of `test` methods in `src` 🙇‍♀️

MET-160 Fix dist structure

---

package.json
turbo.json

Turborepo 2

---

.github/workflows/release.api-common.yml
.github/workflows/release.backend-http-client.yml
.github/workflows/release.background-jobs-common.yml
.github/workflows/release.biome-config.yml
.github/workflows/release.context-fastify-plugins.yml
.github/workflows/release.error-utils.yml
.github/workflows/release.eslint-config.yml
.github/workflows/release.eslint-package-vite-config.yml
.github/workflows/release.events-common.yml
.github/workflows/release.id-utils.yml
.github/workflows/release.non-translatable-markup.yml
.github/workflows/release.prettier-config.yml
.github/workflows/release.prisma-utils.yml
.github/workflows/release.script-utils.yml
.github/workflows/release.supported-languages.yml
.github/workflows/release.universal-ts-utils.yml
.github/workflows/release.websockets-common.yml

turborepo2 requires full package name

Fixing release actions

---

packages/app/prisma-utils/package.json

Syncing prisma version with AP to trigger release

prisma update

---

packages/app/api-common/package.json
packages/app/error-utils/package.json
packages/app/events-common/package.json
packages/app/id-utils/package.json
packages/app/non-translatable-markup/package.json
packages/app/prisma-utils/package.json
packages/app/script-utils/package.json
packages/app/supported-languages/package.json
packages/app/websockets-common/package.json
packages/dev/package-vite-config/package.json

Fixing build

---

.github/workflows/release.healthcheck-utils.yml
packages/app/healthcheck-utils/.gitignore
packages/app/healthcheck-utils/LICENSE.md
packages/app/healthcheck-utils/README.md
packages/app/healthcheck-utils/biome.json
packages/app/healthcheck-utils/package.json
packages/app/healthcheck-utils/src/HealthcheckResultsStore.spec.ts
packages/app/healthcheck-utils/src/HealthcheckResultsStore.ts
packages/app/healthcheck-utils/src/healthchecks.ts
packages/app/healthcheck-utils/src/index.ts
packages/app/healthcheck-utils/tsconfig.json
packages/app/healthcheck-utils/tsconfig.lint.json
packages/app/healthcheck-utils/vitest.config.mts

Extracted from Autopilot and reworked.

Add reusable healthcheck functionality

---

.github/workflows/release.package.yml
packages/app/backend-http-client/package.json
packages/app/background-jobs-common/package.json
packages/app/non-translatable-markup/package.json

Inspired by https://github.com/lokalise/maestro/pull/97

Support multiple releases

---

packages/app/backend-http-client/package.json
packages/app/background-jobs-common/package.json
packages/app/healthcheck-utils/package.json
packages/app/non-translatable-markup/package.json
packages/app/prisma-utils/package.json
packages/app/universal-ts-utils/package.json
packages/dev/package-vite-config/package.json

Applying lint fixes

---

packages/app/non-translatable-markup/src/index.ts
packages/app/non-translatable-markup/src/methods/index.ts

Fixing missing export

---

packages/app/non-translatable-markup/package.json
packages/dev/biome-config/.prettierignore

Fixing lint issue

---

packages/app/background-jobs-common/src/index.ts
packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.spec.ts
packages/app/background-jobs-common/src/periodic-jobs/AbstractPeriodicJob.ts
packages/app/background-jobs-common/src/periodic-jobs/periodicJobTypes.ts
packages/app/background-jobs-common/test/fakes/FakePeriodicJob.ts
packages/app/healthcheck-utils/package.json

Add cron support

---

packages/app/prisma-utils/src/errors/prismaError.ts
packages/app/prisma-utils/src/prismaTransaction.spec.ts
packages/app/prisma-utils/src/prismaTransaction.ts

Context -> https://lokalise.slack.com/archives/C05FLMT3GQK/p1723200833193369

prismaTansaction retrying server closed error

---

packages/app/prisma-utils/src/errors/prismaError.ts
packages/app/prisma-utils/src/prismaTransaction.spec.ts
packages/app/prisma-utils/src/prismaTransaction.ts

Covering isPrismaUnableToStartTransactionInTimeError

---

packages/app/universal-ts-utils/README.md
packages/app/universal-ts-utils/src/array/areStringArraysEqual.spec.ts
packages/app/universal-ts-utils/src/array/areStringArraysEqual.ts

Add new isomorphic util to compare two string arrays

feat: Compare string arrays

---

packages/app/universal-ts-utils/package.json

Add `package-version` script in universal-ts-utils to satisfy Git push job in https://github.com/lokalise/shared-ts-libs/blob/55138aa4394d4163a952758d782edc385e79e6af/.github/workflows/release.package.yml#L62

fix: define package-version script in package.json

---

packages/app/prisma-utils/src/types.ts
packages/app/prisma-utils/tsconfig.json

prisma utils trying to fix build issue

---

packages/app/prisma-utils/package.json

Trying to fix prisma-utils build issue

---

packages/app/prisma-utils/package.json

another prisma-utils build fix

---

packages/app/background-jobs-common/README.md
packages/app/background-jobs-common/package.json
packages/app/background-jobs-common/src/background-job-processor/barrier/barrier.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.barrier.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
packages/app/background-jobs-common/src/index.ts
packages/app/background-jobs-common/test/processors/TestBarrierBackgroundJobProcessor.ts

This should allow us to conditionally throttle jobs

Add support for barriers

---

packages/app/error-utils/package.json

fix error-utils

---

packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts

Fix interval

---

packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
packages/app/prisma-utils/src/prismaClientFactory.spec.ts

get job count lazy init

---

packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts

Improving error report context

---

packages/app/non-translatable-markup/src/methods/isTextTranslatable.spec.ts
packages/app/non-translatable-markup/src/methods/isTextTranslatable.ts
packages/app/non-translatable-markup/src/methods/utils.ts

Context -> https://lokalise.slack.com/archives/C05RU29FQB0/p1724090490026279

Text only with HTML markup is not translatable

---

packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.spec.ts
packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts

Improving bg common logging

---

packages/app/background-jobs-common/src/background-job-processor/constants.ts

From doc:
> Specify which jobs to keep after finishing. If both age and count are specified, then the jobs kept will be the ones that satisfies both properties.
context -> https://lokalise.slack.com/archives/C05E5H778QP/p1725018353605219

Keeping completed jobs a max of 3 days

---

packages/app/universal-ts-utils/src/node.ts

Another try  to fix node import

---

packages/app/error-utils/package.json

This PR is just to trigger a new error-utils release with a bumped bugsnag-js dependency.

Trigger error-utils release

---

packages/app/universal-ts-utils/package.json

Context -> https://publint.dev/@lokalise/universal-ts-utils@2.0.0
Kudos to @ondrejsevcik 🙏

package.json applying recommendations

---

packages/dev/biome-config/configs/biome-esm.jsonc

Biome ESM import rule

---

packages/app/context-fastify-plugins/package.json
packages/app/context-fastify-plugins/src/plugins/opentelemetry/prismaOtelTracingPlugin.ts
packages/app/context-fastify-plugins/src/plugins/requestContextProviderPlugin.ts
packages/app/context-fastify-plugins/src/plugins/unhandledExceptionPlugin.ts

Make plugins compatible with fastify 5

---

.github/workflows/release.metrics-utils.yml
packages/app/metrics-utils/.gitignore
packages/app/metrics-utils/LICENSE.md
packages/app/metrics-utils/README.md
packages/app/metrics-utils/biome.json
packages/app/metrics-utils/package.json
packages/app/metrics-utils/src/AbstractCounterMetric.spec.ts
packages/app/metrics-utils/src/AbstractCounterMetric.ts
packages/app/metrics-utils/src/index.ts
packages/app/metrics-utils/tsconfig.json
packages/app/metrics-utils/tsconfig.lint.json
packages/app/metrics-utils/vite.config.ts

Introduces the `metrics-utils` package to make working with Prom metrics easier and more standardized.

feat(AP-5236): Introduce metrics utils app package

---

packages/app/backend-http-client/package.json
packages/app/background-jobs-common/package.json
packages/app/context-fastify-plugins/package.json
packages/app/error-utils/package.json
packages/app/healthcheck-utils/package.json
packages/app/prisma-utils/package.json
packages/app/script-utils/package.json
packages/app/supported-languages/package.json

Updating to node-core 13

---

packages/app/prisma-utils/package.json

prisma-utils triggering release

---

packages/app/script-utils/package.json

Triggering release on script-utils

---

packages/app/context-fastify-plugins/package.json

context-fastify-plugins triggering release

---

packages/app/healthcheck-utils/package.json

healthcheck release

---

packages/app/supported-languages/package.json

supported-languages release

---

packages/app/backend-http-client/package.json

be http client triggering release

---

packages/app/backend-http-client/package.json

Fixing be-http-client release

---

packages/app/background-jobs-common/package.json
packages/app/background-jobs-common/src/background-job-processor/types.ts

Adjust types to work with newer BullMQ version.
This is semver major, because Omit will not work correctly with older BullMQ versions.

Support newer BullMQ versions

---

packages/app/metrics-utils/package.json

This reduces amount of changes needed to keep the library compatible with future releases

Move fastify-extras to be a peer dependency

---

packages/app/background-jobs-common/package.json
packages/app/background-jobs-common/src/background-job-processor/factories/AbstractBullmqFactory.ts
packages/app/background-jobs-common/src/background-job-processor/factories/CommonBullmqFactory.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
packages/app/background-jobs-common/src/background-job-processor/types.ts

There were some changes around generics in newer BullMQ, this makes our code compatible with it.

Adjust code to support newer bullmq

---

packages/app/prisma-utils/package.json

Prisma range version

---

packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessor.ts
packages/app/background-jobs-common/test/fakes/FakePeriodicJob.ts
packages/app/healthcheck-utils/src/HealthcheckRefreshJob.spec.ts
packages/app/healthcheck-utils/vitest.config.mts

Trying to fix lint

---

packages/app/universal-ts-utils/README.md
packages/app/universal-ts-utils/src/public/array/callChunked.ts
packages/app/universal-ts-utils/src/public/array/chunk.ts
packages/app/universal-ts-utils/src/public/array/isNonEmptyArray.ts
packages/app/universal-ts-utils/src/public/array/removeFalsy.ts
packages/app/universal-ts-utils/src/public/array/removeNullish.ts
packages/app/universal-ts-utils/src/public/array/sort.ts
packages/app/universal-ts-utils/src/public/array/sortByField.ts
packages/app/universal-ts-utils/src/public/array/unique.ts
packages/app/universal-ts-utils/src/public/object/areDeepEqual.ts
packages/app/universal-ts-utils/src/public/object/copyWithoutEmpty.ts
packages/app/universal-ts-utils/src/public/object/copyWithoutNullish.ts
packages/app/universal-ts-utils/src/public/object/deepClone.ts
packages/app/universal-ts-utils/src/public/object/groupBy.ts
packages/app/universal-ts-utils/src/public/object/groupByPath.ts
packages/app/universal-ts-utils/src/public/object/groupByUnique.ts
packages/app/universal-ts-utils/src/public/object/isEmpty.ts
packages/app/universal-ts-utils/src/public/object/pick.ts
packages/app/universal-ts-utils/src/public/object/transformToKebabCase.ts
packages/app/universal-ts-utils/src/public/string/trimText.ts
packages/app/universal-ts-utils/src/public/type/hasMessage.ts
packages/app/universal-ts-utils/src/public/type/isError.ts
packages/app/universal-ts-utils/src/public/type/isObject.ts
packages/app/universal-ts-utils/src/public/type/isStandardizedError.ts
packages/app/universal-ts-utils/src/public/waitAndRetry.ts

Improving some methods doc, standardising it and filling readme

DXP-335 Universal-ts-utils doc

---

packages/dev/biome-config/configs/biome-esm.jsonc
packages/dev/biome-config/package.json

This makes TSX files resolve to JSX and not JS

Use correct extension for components

---

packages/app/universal-ts-utils/README.md
packages/app/universal-ts-utils/src/node.ts
packages/app/universal-ts-utils/src/public/array/uniqueByProperty.spec.ts
packages/app/universal-ts-utils/src/public/array/uniqueByProperty.ts

Adding `uniqueByProperty` array utility function.

feat: add uniqueByProperty array utility function

---

packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
packages/app/background-jobs-common/src/background-job-processor/managers/types.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.spy.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.start.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/types.ts
packages/app/background-jobs-common/test/processors/TestOverrideProcessBackgroundProcessor.ts

Adding some basic type tests

---

packages/app/background-jobs-common/src/background-job-processor/processors/FakeBackgroundJobProcessorNew.ts

Fix fake processor deps

---

packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.spec.ts
packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.ts

Improving queue manager type

---

packages/app/background-jobs-common/README.md
packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts

Replace undefined arg with a boolean for QueueManager to start

fix: Update QueueManager.ts start args

---

packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.spec.ts
packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts

We will need this to resolve route path for fastify definitions

Resolve path from route definition

---

packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts

We don't care about any of the types on this parameter

Fix method generic

---

packages/app/prisma-utils/package.json
packages/app/universal-ts-utils/src/public/api-contracts/apiContracts.ts

Needed for DELETE method supports in fastify routes

Add more any

---

packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
packages/app/background-jobs-common/src/background-job-processor/managers/types.ts

Adding support for zod defaults

queue manager allow zod default

---

packages/app/fastify-api-contracts/package.json
packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts
packages/app/fastify-api-contracts/src/index.ts

Documentation and release pipeline coming in the next PR.

feat: support remaining HTTP methods for fastify api contracts

---

.github/workflows/release.fastify-api-contracts.yml
packages/app/fastify-api-contracts/README.md
packages/app/fastify-api-contracts/package.json
packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
packages/app/frontend-http-client/package.json
packages/app/universal-ts-utils/README.md

Basic usage example, will add more details later

Document fastify-api-contracts usage

---

packages/app/fastify-api-contracts/package.json

Trying to fix issue by using default exports

---

packages/app/fastify-api-contracts/biome.json
packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
packages/app/fastify-api-contracts/src/index.ts

This fixes package usage in ESM projects

Enforce ESM imports

---

packages/app/fastify-api-contracts/README.md
packages/app/fastify-api-contracts/src/fastifyApiContracts.spec.ts
packages/app/fastify-api-contracts/src/fastifyApiRequestInjector.ts

Encourage developers to use reusable logic for injecting headers

Support header factory

---

packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.deduplication.spec.ts
packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
packages/app/background-jobs-common/src/background-job-processor/managers/types.ts
packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.spec.ts
packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.start.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts
packages/app/background-jobs-common/src/background-job-processor/utils.ts
packages/app/background-jobs-common/test/TestDependencyFactory.ts

Fixing issues with deduplication ttl type and delayed jobs in test mode

---

packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.spec.ts
packages/app/background-jobs-common/src/background-job-processor/utils.ts

backoff delay as 1 for tests

---

packages/app/non-translatable-markup/src/methods/removeNonTranslatableTags.spec.ts
packages/app/non-translatable-markup/src/methods/removeNonTranslatableTags.ts
packages/app/non-translatable-markup/src/methods/utils.ts

adjust NT tags regex

---

packages/app/context-fastify-plugins/package.json

Updating opentelemetry deps

---

packages/dev/package-vite-config/package.config.ts
packages/dev/package-vite-config/package.json

package-vite-config vitest 3

---

packages/app/non-translatable-markup/src/methods/extractTextBetweenTags.spec.ts
packages/app/non-translatable-markup/src/methods/isAttemptToEditNonTranslatableContent.spec.ts
packages/app/non-translatable-markup/src/methods/isTextTranslatable.spec.ts
packages/app/non-translatable-markup/src/methods/removeNonTranslatableTags.spec.ts
packages/app/non-translatable-markup/src/methods/utils.ts

* adjust removeNonTranslatableTags logic

---

packages/app/frontend-http-client/src/client.ts

I just really need npm to publish a new version - this is a change that will force that to happen

minor: we need to trigger an npm publish and we don't have any methods, hence removing the comment

---

packages/app/backend-http-client/README.md
packages/app/backend-http-client/index.ts
packages/app/backend-http-client/package.json
packages/app/backend-http-client/src/client/apiContractTypes.ts
packages/app/backend-http-client/src/client/httpClient.spec.ts
packages/app/backend-http-client/src/client/httpClient.ts
packages/app/backend-http-client/tsconfig.json

Will add non-payload requests in the follow-up PR.

feat: Support API contracts for payload requests in backend-http-client

---

packages/app/api-common/package.json
packages/app/backend-http-client/package.json
packages/app/fastify-api-contracts/package.json
packages/app/id-utils/package.json
packages/app/universal-ts-utils/package.json

Removing not needed noEmit

---

packages/app/backend-http-client/package.json
packages/app/backend-http-client/src/index.ts
packages/app/backend-http-client/vitest.config.mts

Fixing index issue for be-http-client

---

packages/app/prisma-utils/package.json

Trying to fix tests

---

packages/app/script-utils/biome.json
packages/app/script-utils/package.json
packages/app/script-utils/src/index.ts
packages/app/script-utils/src/vault/syncEnvWithVault.spec.ts
packages/app/script-utils/src/vault/syncEnvWithVault.ts
packages/app/script-utils/tsconfig.build.json
packages/app/script-utils/tsconfig.json
packages/app/script-utils/tsconfig.lint.json
packages/app/script-utils/vite.config.ts

chore: script-utils using shared tsconfig

---

packages/app/background-jobs-common/package.json
packages/app/background-jobs-common/tsconfig.json
packages/app/healthcheck-utils/tsconfig.json

redis-semaphore 5.6.2

---

packages/app/api-contracts/README.md

docs: Fix documentation for api contract module augmentation

---

packages/app/frontend-http-client/README.md
packages/app/frontend-http-client/package.json
packages/app/frontend-http-client/src/client.spec.ts
packages/app/frontend-http-client/src/client.ts

Switch fe-client to api-contracts

---

packages/app/backend-http-client/README.md
packages/app/backend-http-client/package.json
packages/app/backend-http-client/src/client/apiContractTypes.ts
packages/app/backend-http-client/src/client/httpClient.spec.ts
packages/app/backend-http-client/src/client/httpClient.ts

Migrate be client to api contracts lib

---

packages/app/fastify-api-contracts/src/fastifyApiContracts.ts
packages/app/fastify-api-contracts/src/types.ts

Revert changes in @lokalise/fastify-api-contracts and unblock a release of @lokalise/api-contracts first. There will be a separate change for @lokalise/fastify-api-contracts.

chore: Unblock npm release 1/2

---

packages/app/api-contracts/README.md
packages/app/api-contracts/src/__snapshots__/apiContracts.spec.ts.snap
packages/app/api-contracts/src/apiContracts.ts
packages/app/universal-ts-utils/README.md

Add summary to route contracts in @lokalise/api-contracts

chore: Add summary to api-contracts 2/4

---

packages/app/universal-ts-utils/README.md

Force a release of @lokalise/universal-ts-utils

chore: Add summary to api-contracts 3/4

---

.github/workflows/release.api-common.yml
.github/workflows/release.package.yml
packages/app/api-common/vitest.config.ts

Test bot access token

---

.github/workflows/release.package.yml
packages/app/api-common/vitest.config.ts

Test using bot access token

---

.github/workflows/release.api-common.yml
.github/workflows/release.package.yml

Revert changes on release actions

---

.github/workflows/release.mockttp-utils.yml
packages/app/mockttp-utils/.gitignore
packages/app/mockttp-utils/LICENSE.md
packages/app/mockttp-utils/README.md
packages/app/mockttp-utils/package.json
packages/app/mockttp-utils/src/index.ts
packages/app/mockttp-utils/src/mockttpUtils.spec.ts
packages/app/mockttp-utils/src/mockttpUtils.ts
packages/app/mockttp-utils/tsconfig.build.json
packages/app/mockttp-utils/tsconfig.json
packages/app/mockttp-utils/vitest.config.ts

Wrapper for mockttp + api contracts

feat: First version of mockttp utils

---

packages/app/api-contracts/package.json
packages/app/api-contracts/src/__snapshots__/apiContracts.spec.ts.snap
packages/app/api-contracts/src/apiContracts.ts

Adds support by tags, useful for OpenAPI definitions

feat: Add support for tags

---

packages/app/healthcheck-utils/src/HealthcheckRefreshJob.spec.ts
packages/app/healthcheck-utils/src/HealthcheckResultsStore.spec.ts
packages/app/healthcheck-utils/src/HealthcheckResultsStore.ts
packages/app/healthcheck-utils/src/healthchecks.ts

* return false on empty healthcheck

---

packages/app/aws-config/package.json

Fix typo in peer dep condition

---

packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsOptionsResolver.ts
packages/app/aws-config/src/message-queue-toolkit/MessageQueueToolkitSnsResolver.spec.ts
packages/app/aws-config/src/message-queue-toolkit/types.ts

Fixing issues with message types

---

packages/app/universal-testing-utils/README.md
packages/app/universal-testing-utils/src/MswHelper.spec.ts
packages/app/universal-testing-utils/src/MswHelper.ts
packages/app/universal-testing-utils/vitest.config.ts

Add helper methods for invalid responses and wildcard paths

feat Add extra msw test methods

---

packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.spec.ts
packages/app/background-jobs-common/src/background-job-processor/managers/QueueRegistry.ts
packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.spec.ts
packages/app/background-jobs-common/src/background-job-processor/monitoring/BackgroundJobProcessorMonitor.ts
packages/app/background-jobs-common/src/background-job-processor/monitoring/registerActiveQueueIds.spec.ts
packages/app/background-jobs-common/src/background-job-processor/monitoring/registerActiveQueueIds.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.ts

Respecting grouping on active queue ids

Active queue ids issue

---

packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts

Narrowing down queue config type

---

packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.ts

Adding resolved queue id getter to old processor

---

.github/workflows/ci.yml

Adds 24 to Node version matrix

chore: Add Node 24

---

packages/app/background-jobs-common/package.json

node-core 14 on bj-jobs-common

---

packages/app/context-fastify-plugins/package.json

context-fastify-plugin -> node-core 14

---

packages/app/healthcheck-utils/package.json

healtchech-utils node-core 14

---

packages/app/prisma-utils/package.json

prisma-utils node-core 14

---

packages/app/script-utils/package.json

script-utils node-core 14

---

packages/app/aws-config/package.json
packages/app/backend-http-client/package.json
packages/app/error-utils/package.json
packages/app/healthcheck-utils/package.json
packages/app/supported-languages/package.json

Dev dependencies updated

---

packages/app/aws-config/src/message-queue-toolkit/utils.spec.ts
packages/app/aws-config/src/message-queue-toolkit/utils.ts

* change queue name validation logic

---

packages/app/universal-testing-utils/README.md
packages/app/universal-testing-utils/src/MswHelper.spec.ts
packages/app/universal-testing-utils/src/MswHelper.ts
packages/app/universal-testing-utils/test/testContracts.ts

AP-7179 allow passing custom callback to `MswHelper`

---

packages/app/background-jobs-common/src/background-job-processor/managers/QueueManager.ts
packages/app/background-jobs-common/src/background-job-processor/managers/types.ts

Fixing the job options callback type

---

packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessor.spec.ts
packages/app/background-jobs-common/src/background-job-processor/processors/AbstractBackgroundJobProcessorNew.stalled.spec.ts

There is failing test: https://github.com/lokalise/shared-ts-libs/actions/runs/15419026404/job/43388844592?pr=632. This PR unblocks a release of https://github.com/lokalise/shared-ts-libs/pull/632

fix: Compare attempts made with number of attempts from opts

---

packages/app/zod-extras/package.json
packages/app/zod-extras/src/utils/numberSplitFactory.test.ts
packages/app/zod-extras/src/utils/stringSplitFactory.test.ts
packages/app/zod-extras/src/utils/toArrayPreprocessor.test.ts
packages/app/zod-extras/src/utils/toBooleanPreprocessor.test.ts
packages/app/zod-extras/src/utils/toDatePreprocessor.test.ts
packages/app/zod-extras/src/utils/toNumberPreprocessor.test.ts
packages/app/zod-extras/src/utils/toStringPreprocessor.test.ts

Run zod-extras tests with zod v4

Run tests with zod v4

---

packages/app/api-common/package.json
packages/app/api-common/src/apiSchemas.spec.ts
packages/app/api-common/src/apiSchemas.ts
packages/app/api-common/vitest.config.ts

chore: migrate api-commons to zod v4 

---

packages/app/fastify-bullboard-plugin/package.json

Fix releases by adding missing scripts

Fix bullboard releases

---

packages/app/fastify-bullboard-plugin/src/basicAuth.ts

Adjust skiplist logic not to trigger in wrong cases

Fix skiplist logic

---

packages/app/universal-ts-utils/package.json
packages/app/universal-ts-utils/src/public/array/chunk.ts
packages/app/universal-ts-utils/src/public/waitAndRetry.ts

Library no longer uses zod for anything

Remove zod dependency, update deps

---

packages/app/fastify-bullboard-plugin/src/errorReporterPlugin.ts

Fixing pino import

---

packages/app/aws-config/tests/FakeLogger.ts

Lint fix in aws-config

---

packages/app/background-jobs-common/src/background-job-processor/logger/BackgroundJobProcessorLogger.spec.ts
packages/app/background-jobs-common/src/background-job-processor/logger/BackgroundJobProcessorLogger.ts

Fixing -> https://github.com/lokalise/shared-ts-libs/actions/runs/16833052055/job/47685417136?pr=708

Fixing type issue in bg-jobs-common

---

packages/app/background-jobs-common/src/background-job-processor/monitoring/backgroundJobProcessorGetActiveQueueIds.ts

Var name improvement to reduce confusion

---

packages/app/api-common/src/apiSchemas.ts

added after pagination schema

---

packages/app/api-contracts/src/apiContracts.spec.ts
packages/app/api-contracts/src/apiContracts.ts

Simplifies test suite descriptions

Add helper util for generating route description

---

packages/app/universal-testing-utils/README.md
packages/app/universal-testing-utils/src/MockttpHelper.spec.ts
packages/app/universal-testing-utils/src/MockttpHelper.ts

Add support for testing error cases for mockttphelper

---

packages/app/universal-ts-utils/README.md
packages/app/universal-ts-utils/src/node.ts
packages/app/universal-ts-utils/src/public/iterable/collectFromIterable.spec.ts
packages/app/universal-ts-utils/src/public/iterable/collectFromIterable.ts

Adding `collectFromIterable` utility

feat: Collect from iterable utility
